
name: CI Test

# Defines environmental variables
env:
  GO_VERSION: '1.22.2'
  SERVICE_NAME: 'service-template'

# Controls when the action will run
on:
  pull_request:
    branches:
      - main

# A series of workflow jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build and Test

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout source
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    # Setup the Go environment
    - name: Setup Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: "${{ env.GO_VERSION }}"

    # Build the container so TestContainers has something to run
    - name: Build Docker container
      run: docker build -t "${{ env.SERVICE_NAME }}" .

    # Run the tests
    - name: Test with the Go CLI
      run: go test
